greeting:
  message: "hello World"
consul:
  host: localhost
  port: 8500
quarkus:
  stork:
    my-service:
      service-discovery:
        type: consul
        consul-host: localhost
        consul-port: 8500
      load-balancer:
        type: round-robin
  nacos-config:
    enabled: true
    app-id: demo-example
    format: yml
    server-addr: 10.200.90.84:8848
    username: eccom
    password: Eccom@123
  datasource:
    db-kind: postgresql
    db-name:
    username: quarkus_test
    password: quarkus_test
    reactive:
      url: postgresql://localhost:5432/quarkus_test
  rest-client:
    extensions-api:
      url: https://stage.code.quarkus.io/api
      scope: jakarta.inject.Singleton
      verify-host: false
    localhost-api:
      url: http://localhost:8080
      scope: jakarta.inject.Singleton
      verify-host: false
