greeting:
  message: "hello World"
quarkus:
  datasource:
    db-kind: postgresql
    db-name:
    username: quarkus_test
    password: quarkus_test
    reactive:
      url: postgresql://localhost:5432/quarkus_test
  rest-client:
    extensions-api:
      url: https://stage.code.quarkus.io/api
      scope: jakarta.inject.Singleton
      verify-host: false
    localhost-api:
      url: http://localhost:8080
      scope: jakarta.inject.Singleton
      verify-host: false